# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('visitinfo', models.CharField(max_length=2000)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
