# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patientvisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientvisit',
            name='reporter',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='patients.Patient'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientvisit',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='patientvisit',
            name='visitinfo',
            field=models.TextField(max_length=2000),
        ),
    ]
