# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_auto_20170916_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientvisit',
            old_name='reporter',
            new_name='patient',
        ),
    ]
