# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_auto_20170916_1435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientvisit',
            options={'ordering': ['-patient']},
        ),
    ]
