# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_auto_20170916_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientvisit',
            options={'ordering': ['-visit_date']},
        ),
        migrations.RenameField(
            model_name='patientvisit',
            old_name='date',
            new_name='visit_date',
        ),
    ]
