# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_auto_20170916_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientvisit',
            old_name='visitinfo',
            new_name='visit_info',
        ),
        migrations.RemoveField(
            model_name='patientvisit',
            name='patient',
        ),
        migrations.AlterField(
            model_name='patientvisit',
            name='visit_date',
            field=models.DateField(),
        ),
    ]
