# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_auto_20170916_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientvisit',
            name='patient',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='patients.Patient'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientvisit',
            name='visit_date',
            field=models.CharField(max_length=50),
        ),
    ]
