# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 15:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_remove_patientvisit_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientvisit',
            name='patient',
            field=models.ForeignKey(default=datetime.datetime(2017, 9, 16, 15, 0, 2, 335974, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='patients.Patient'),
            preserve_default=False,
        ),
    ]
