# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_patientvisit_patient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientvisit',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='patientvisit',
            old_name='visit_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='patientvisit',
            old_name='visit_info',
            new_name='info',
        ),
    ]
