# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_auto_20170916_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientvisit',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
