# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 13:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0014_patient_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientvisit',
            old_name='info',
            new_name='referral_reason',
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='diagnosis',
            field=models.TextField(default='New', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='service_requested',
            field=models.TextField(default='New', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='service_type_requested',
            field=models.TextField(default='New', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
