# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_auto_20170919_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientvisit',
            name='diagnosis',
            field=models.TextField(default='Anonymous', max_length=1000),
        ),
        migrations.AlterField(
            model_name='patientvisit',
            name='referral_reason',
            field=models.TextField(default='Anonymous', max_length=2000),
        ),
        migrations.AlterField(
            model_name='patientvisit',
            name='service_requested',
            field=models.TextField(default='Anonymous', max_length=200),
        ),
        migrations.AlterField(
            model_name='patientvisit',
            name='service_type_requested',
            field=models.TextField(default='Anonymous', max_length=200),
        ),
        migrations.AlterField(
            model_name='patientvisit',
            name='user_id',
            field=models.TextField(default='Anonymous', verbose_name='auth.User'),
        ),
    ]
