# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0017_remove_patientvisit_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientvisit',
            name='user_id',
            field=models.TextField(default='Anonymous', verbose_name='auth.User'),
        ),
    ]
