# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0018_patientvisit_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientvisit',
            name='user_id',
            field=models.TextField(verbose_name='auth.User'),
        ),
    ]
