# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0019_auto_20170923_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.TextField(default='Anonymous', max_length=100)),
                ('service_infomatiom', models.TextField(default='Anonymous', max_length=200)),
            ],
            options={
                'ordering': ['-service'],
            },
        ),
    ]
