# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 08:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0020_doctorservices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorservices',
            old_name='service_infomatiom',
            new_name='service_information',
        ),
    ]
