# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0021_auto_20170930_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientvisit',
            name='service_requested',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.DoctorServices'),
        ),
    ]
