# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic_date',
            name='clinic_type',
            field=models.CharField(default='general', max_length=100),
            preserve_default=False,
        ),
    ]
