# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 11:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0022_auto_20170930_1115'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinic', '0002_clinic_date_clinic_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic_Date_Patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clinic.Clinic_Date')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.Patient')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-clinic'],
            },
        ),
    ]
