# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_referral', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor_referral',
            old_name='details',
            new_name='booking_date',
        ),
        migrations.AddField(
            model_name='doctor_referral',
            name='doctor_id',
            field=models.TextField(default='patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor_referral',
            name='patient_id',
            field=models.TextField(default='patient'),
            preserve_default=False,
        ),
    ]
