# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 11:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor_referral', '0003_auto_20170904_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_referral',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor_referral',
            name='booked_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor_referral',
            name='comments',
            field=models.CharField(default='None', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor_referral',
            name='group',
            field=models.CharField(default='None', max_length=250),
            preserve_default=False,
        ),
    ]
