# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 08:16
from __future__ import unicode_literals

from django.db import migrations, models
import doctor_referral.models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_referral', '0004_auto_20170904_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_referral',
            name='booked_date',
            field=models.DateTimeField(validators=[doctor_referral.models.validate_booked_date]),
        ),
    ]
