# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 08:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0022_auto_20170930_1115'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.TextField(blank=True, max_length=500)),
                ('location', models.TextField(blank=True, max_length=500)),
                ('full_name', models.TextField(blank=True, max_length=500)),
                ('doctor_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.DoctorServices')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
