# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 15:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.TextField(default='Anonymous', max_length=100)),
                ('service_information', models.TextField(default='Anonymous', max_length=200)),
            ],
            options={
                'ordering': ['-service'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('phonenumber', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-firstname'],
            },
        ),
        migrations.CreateModel(
            name='PatientVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('diagnosis', models.TextField(default='Anonymous', max_length=1000)),
                ('user_id', models.TextField(verbose_name='auth.User')),
                ('service_type_requested', models.TextField(default='Anonymous', max_length=200)),
                ('referral_reason', models.TextField(default='Anonymous', max_length=2000)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Patient')),
                ('service_requested', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.DoctorServices')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
