# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 15:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import doctor_referral.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic_ReferralDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(max_length=100)),
                ('clinic_details', models.CharField(max_length=1000)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('clinic_date', models.DateTimeField(validators=[doctor_referral.validators.validate_booked_date])),
                ('doctor_accept', models.CharField(max_length=250)),
                ('clinic_accept', models.CharField(max_length=1000)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-clinic_date'],
            },
        ),
        migrations.CreateModel(
            name='Doctor_Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=50)),
                ('doctor_id', models.CharField(max_length=50)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('booked_date', models.DateTimeField(validators=[doctor_referral.validators.validate_booked_date])),
                ('group', models.CharField(max_length=250)),
                ('comments', models.CharField(max_length=1000)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-booking_date'],
            },
        ),
    ]
